name: Build docker image

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          VERSION=`curl -L -s https://dl.k8s.io/release/stable.txt`
          docker build -t gaetancollaud/kubectl:latest .
          docker build -t gaetancollaud/kubectl:$VERSION .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        run: |
          VERSION=`curl -L -s https://dl.k8s.io/release/stable.txt`
          docker push gaetancollaud/kubectl:latest
          docker push gaetancollaud/kubectl:$VERSION
